import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/create.module.css'
import Header from '../components/header'
import Cal from '../components/calendar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleSubmit = (event: any) => {
    event.preventDefault();

};

  return (
    <>
      <Head>
        <title>Make tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header />
        <div className={styles.description}>
            <form className={`${styles.form}`} onSubmit={handleSubmit}>
              <div className={`${styles.row}`}>
                <div className={`${styles.fix}`}>{/*date*/}
                    <div className={`${styles.calc}`}>
                        <Cal />
                    </div>
                </div>
                <div className={`${styles.formatting}`}>{/*viss parejais*/}
                    <label className={`${styles.label}`}>
                      Title
                      <input type="text" className={`${styles.input}`} />
                    </label>
                    <label className={`${styles.labelA}`}>
                      Description
                      <textarea cols={50} rows={5} className={`${styles.inputA}`}></textarea>
                    </label>
                </div>
              </div>
              <button type="submit" className={`${styles.button}`}>Submit</button>
            </form>
        </div>
      </main>
    </>
  )
}

